version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        identifier: raw_gz_sales
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: ordersid primary key
            tests:
              - unique
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez / we have on row per product_id with his purchase cost
        columns:
          - name: products_id
            description: ordersid primary key
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: ship costs of Greenweez / we have costs per orders_id
        columns:
          - name: orders_id
            description: ordersid primary key
            tests:
              - unique
              - not_null
